#!/usr/bin/node

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
/*jslint plusplus: true */
(function twelve(limit) {
    "use strict";
    var ini = new Date().getTime(), end = false, n = 0, triangularNumber = 0, totalDivisors = 0, divisors = function numberOfDivisors(number) {
        var numbers = 1, n, max = parseInt(number / 2, 10) + 1;
        for (n = 1; n < max; n++) {
            if (number % n === 0) {
                numbers++;
            }
        }
        return numbers;
    }
    while((totalDivisors = divisors(triangularNumber += ++n)) < limit);
    console.log("percorremos", n, "números triangulares para encontrar o primeiro divisivel por", limit, "ou mais números que é", triangularNumber, "tem", totalDivisors);
    end = new Date().getTime();
    console.log(arguments.callee.name, 'on', (end - ini) / 1000, 'seconds');
})(500);