#!/usr/bin/node
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
// #!/usr/bin/node
// --- Ignore this (I like *nix SOs and use NodeJS)

var fibonacci = function (lim) {
	// --- Declaration of our main function

	var x = 1, ant = tmp = 0, even_sum = 0;
	// --- Declaration and inicialization of our vars

	while (x < lim)
	{
		tmp = x;
		x += ant;
		ant = tmp;
		// --- Standart Fibonacci algorithm

		if (x % 2 == 0) even_sum += x;
		// --- Basic validation to increase our evens found
	}
	return even_sum;
}

console.log(fibonacci(4000000));
// --- Print results